# -*- coding: utf-8 -*-
"""MiniProject_ATM_OOPS_B.V.V.SURYA DURGA PRASAD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11slotMUngX3FuDvDKTmYlFs6p89j_tyS
"""

from abc import ABC, abstractmethod
#Abstract class
class BankAccount(ABC):

   def __init__(self, account_number, balance):
        self.account_number = account_number
        #Encapsulation
class Account:
   def __init__(self, name, acc_no, balance):
      self.name = name            #public
      self._acc_no = acc_no       #protected
      self.__balance = balance    #privte
       #get current balance
   def get_blance(self):
       return self.__balance
     #update balance
   def set_balance(self, amount):
       self.__balance = amount
       #Inheritance + Polymorphism
class ATM(Account, BankAccount):
      MAX_WITHDRAW_LIMIT = 10000 #max withdrawal
      def bank_name(cls):
          print("---------------------------------")
          print("WELCOME TO SURYA NATIONAL BANK")
          print("---------------------------------")
           #check whether amount is valid
      def validate_amount(amount):
          return amount > 0
            #show current balance
      def check_balance(self):
          print(f"Current Balance: {self.get_blance()}")
           #deposit money
      def deposit(self, amount):
          if amount > 0:
              self.set_balance(self.get_blance() + amount)
              print("Deposit Successfull")
              self.check_balance()
          else:
              print("Invalid deposit amount")
             #withdraw money with checks
      def withdraw(self, amount):
          if not ATM.validate_amount(amount):
              print("Invalid withdrawal amount")
          elif amount > ATM.MAX_WITHDRAW_LIMIT:
              print("Maximum withdrawl limit is: ₹{ATM.MAX_WITHDRAW_LIMIT}")
          elif amount > self.get_blance():
              print("Insufficient balance")
          else:
              self.set_balance(self.get_blance() - amount)
              print("Withdrawal Successfull")
              self.check_balance()
      def transaction(self):
          print("ATM Transaction started successfully")
  #Main program
atm = ATM("burid", 18113, 1500.56)
atm.bank_name()
entered_pin = input("Enter your pin: ")
if entered_pin == "2006":
   print("Pin validated")
   atm.transaction()

   while True:
        print("""
-----------------------------
ATM MENU
1. Check Balance
2. Deposit Money
3. Withdraw Money
4. Account Details
5. Exit
-----------------------------
""")

        choice = int(input("enter yout choice: "))
        if choice == 1:
            atm.check_balance()

        elif choice == 2:
            amt = int(input("enter amount to deposit: "))
            atm.deposit(amt)
        elif choice == 3:
            amt = int(input("enter amount to withdraw: "))
            atm.withdraw(amt)
        elif choice == 4:
            print("ACCOUNT HOLDER:",atm.name)
            print("ACCOUNT NUMBER:",atm._acc_no)
            print(f"Maximum withdrawl limit is: ₹{ATM.MAX_WITHDRAW_LIMIT}")

        elif choice == 5:
            print("THANK YOU FOR USING SURYA NATIONAL BANK ATM")
            break
        else:
            print("INVALID CHOICE. TRY AGAIN.")
else:
    print("INCORRECT PIN. ACESS DENIED.")